// Local static schema metadata only. These simplified names are for query-building practice.
// Column types let the app choose safer operators and value formatting.
const SOC_SCHEMAS = [
  {
    category: "Microsoft Defender for Endpoint",
    table: "DeviceProcessEvents",
    description: "Process creation events from endpoints. Useful for reviewing command lines, parent processes, accounts, and suspicious execution.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "DeviceName", "ActionType", "FileName", "ProcessCommandLine", "InitiatingProcessFileName"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "DeviceName", type: "string" },
      { name: "DeviceId", type: "string" },
      { name: "ActionType", type: "string" },
      { name: "FileName", type: "string" },
      { name: "FolderPath", type: "string" },
      { name: "ProcessCommandLine", type: "string" },
      { name: "InitiatingProcessFileName", type: "string" },
      { name: "InitiatingProcessCommandLine", type: "string" },
      { name: "InitiatingProcessParentFileName", type: "string" },
      { name: "AccountName", type: "string" },
      { name: "AccountDomain", type: "string" },
      { name: "ReportId", type: "long" }
    ]
  },
  {
    category: "Microsoft Defender for Endpoint",
    table: "DeviceNetworkEvents",
    description: "Network connection events from endpoints. Useful for reviewing remote URLs, IP addresses, ports, protocol, and the process that made the connection.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "DeviceName", "ActionType", "InitiatingProcessFileName", "RemoteUrl", "RemoteIP", "RemotePort"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "DeviceName", type: "string" },
      { name: "DeviceId", type: "string" },
      { name: "ActionType", type: "string" },
      { name: "InitiatingProcessFileName", type: "string" },
      { name: "InitiatingProcessCommandLine", type: "string" },
      { name: "RemoteUrl", type: "string" },
      { name: "RemoteIP", type: "string" },
      { name: "RemotePort", type: "int" },
      { name: "LocalIP", type: "string" },
      { name: "LocalPort", type: "int" },
      { name: "Protocol", type: "string" },
      { name: "ReportId", type: "long" }
    ]
  },
  {
    category: "Microsoft Defender for Endpoint",
    table: "DeviceFileEvents",
    description: "File activity events from endpoints. Useful for reviewing file names, paths, hashes, actions, accounts, and the process that touched a file.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "DeviceName", "ActionType", "FileName", "FolderPath", "InitiatingProcessFileName"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "DeviceName", type: "string" },
      { name: "DeviceId", type: "string" },
      { name: "ActionType", type: "string" },
      { name: "FileName", type: "string" },
      { name: "FolderPath", type: "string" },
      { name: "SHA256", type: "string" },
      { name: "InitiatingProcessFileName", type: "string" },
      { name: "InitiatingProcessCommandLine", type: "string" },
      { name: "AccountName", type: "string" },
      { name: "ReportId", type: "long" }
    ]
  },
  {
    category: "Microsoft Defender for Endpoint",
    table: "DeviceRegistryEvents",
    description: "Registry activity from endpoints. Useful for checking persistence paths, modified values, accounts, and the process that changed a key.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "DeviceName", "ActionType", "RegistryKey", "RegistryValueName", "InitiatingProcessFileName"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "DeviceName", type: "string" },
      { name: "DeviceId", type: "string" },
      { name: "ActionType", type: "string" },
      { name: "RegistryKey", type: "string" },
      { name: "RegistryValueName", type: "string" },
      { name: "RegistryValueData", type: "string" },
      { name: "InitiatingProcessFileName", type: "string" },
      { name: "InitiatingProcessCommandLine", type: "string" },
      { name: "AccountName", type: "string" },
      { name: "ReportId", type: "long" }
    ]
  },
  {
    category: "Microsoft Defender for Endpoint",
    table: "DeviceLogonEvents",
    description: "Endpoint logon activity. Useful for reviewing account usage, logon type, remote source, and local admin sign-ins.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "DeviceName", "ActionType", "AccountName", "LogonType", "RemoteIP", "IsLocalAdmin"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "DeviceName", type: "string" },
      { name: "DeviceId", type: "string" },
      { name: "ActionType", type: "string" },
      { name: "AccountName", type: "string" },
      { name: "AccountDomain", type: "string" },
      { name: "LogonType", type: "string" },
      { name: "RemoteIP", type: "string" },
      { name: "RemoteDeviceName", type: "string" },
      { name: "IsLocalAdmin", type: "bool" },
      { name: "ReportId", type: "long" }
    ]
  },
  {
    category: "Microsoft Defender for Endpoint",
    table: "DeviceImageLoadEvents",
    description: "Image load events from endpoints. Useful for reviewing loaded files, paths, hashes, and the initiating process.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "DeviceName", "ActionType", "FileName", "FolderPath", "InitiatingProcessFileName"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "DeviceName", type: "string" },
      { name: "DeviceId", type: "string" },
      { name: "ActionType", type: "string" },
      { name: "FileName", type: "string" },
      { name: "FolderPath", type: "string" },
      { name: "SHA256", type: "string" },
      { name: "InitiatingProcessFileName", type: "string" },
      { name: "InitiatingProcessCommandLine", type: "string" },
      { name: "ReportId", type: "long" }
    ]
  },
  {
    category: "Microsoft Defender for Endpoint",
    table: "DeviceEvents",
    description: "General endpoint events. Useful for reviewing action types, additional fields, accounts, and initiating process context.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "DeviceName", "ActionType", "AccountName", "InitiatingProcessFileName", "AdditionalFields"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "DeviceName", type: "string" },
      { name: "DeviceId", type: "string" },
      { name: "ActionType", type: "string" },
      { name: "AdditionalFields", type: "dynamic" },
      { name: "InitiatingProcessFileName", type: "string" },
      { name: "InitiatingProcessCommandLine", type: "string" },
      { name: "AccountName", type: "string" },
      { name: "ReportId", type: "long" }
    ]
  },
  {
    category: "Microsoft Defender for Endpoint",
    table: "DeviceInfo",
    description: "Endpoint inventory and posture information. Useful for reviewing platform, risk, exposure, onboarding, and public IP context.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "DeviceName", "OSPlatform", "MachineGroup", "ExposureLevel", "RiskScore", "OnboardingStatus"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "DeviceName", type: "string" },
      { name: "DeviceId", type: "string" },
      { name: "OSPlatform", type: "string" },
      { name: "OSVersion", type: "string" },
      { name: "MachineGroup", type: "string" },
      { name: "ExposureLevel", type: "string" },
      { name: "RiskScore", type: "string" },
      { name: "OnboardingStatus", type: "string" },
      { name: "PublicIP", type: "string" }
    ]
  },
  {
    category: "Microsoft Defender for Endpoint",
    table: "AlertInfo",
    description: "Alert summary information. Useful for reviewing alert title, severity, category, service source, and mapped techniques.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "AlertId", "Title", "Severity", "Category", "ServiceSource"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "AlertId", type: "string" },
      { name: "Title", type: "string" },
      { name: "Category", type: "string" },
      { name: "Severity", type: "string" },
      { name: "ServiceSource", type: "string" },
      { name: "DetectionSource", type: "string" },
      { name: "AttackTechniques", type: "string" }
    ]
  },
  {
    category: "Microsoft Defender for Endpoint",
    table: "AlertEvidence",
    description: "Alert evidence entities. Useful for pivoting from alerts to devices, files, accounts, network indicators, and evidence roles.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "AlertId", "EntityType", "EvidenceRole", "DeviceName", "FileName", "AccountName"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "AlertId", type: "string" },
      { name: "EntityType", type: "string" },
      { name: "EvidenceRole", type: "string" },
      { name: "DeviceName", type: "string" },
      { name: "FileName", type: "string" },
      { name: "FolderPath", type: "string" },
      { name: "SHA256", type: "string" },
      { name: "RemoteIP", type: "string" },
      { name: "RemoteUrl", type: "string" },
      { name: "AccountName", type: "string" }
    ]
  },
  {
    category: "Microsoft Entra ID",
    table: "SigninLogs",
    description: "Interactive sign-in events. Useful for reviewing users, applications, locations, result details, conditional access, and risk context.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "UserPrincipalName", "AppDisplayName", "ResultType", "IPAddress", "ConditionalAccessStatus"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "UserPrincipalName", type: "string" },
      { name: "UserDisplayName", type: "string" },
      { name: "AppDisplayName", type: "string" },
      { name: "IPAddress", type: "string" },
      { name: "Location", type: "string" },
      { name: "ResultType", type: "string" },
      { name: "ResultDescription", type: "string" },
      { name: "ConditionalAccessStatus", type: "string" },
      { name: "RiskLevelAggregated", type: "string" },
      { name: "RiskState", type: "string" },
      { name: "AuthenticationRequirement", type: "string" },
      { name: "DeviceDetail", type: "dynamic" },
      { name: "Status", type: "dynamic" }
    ]
  },
  {
    category: "Microsoft Entra ID",
    table: "EntraIdSignInEvents",
    description: "Entra ID sign-in events in an endpoint-style schema. Useful for reviewing account, app, location, device, and risk details.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "AccountUpn", "Application", "IPAddress", "ErrorCode", "FailureReason", "RiskLevelAggregated"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "AccountUpn", type: "string" },
      { name: "AccountDisplayName", type: "string" },
      { name: "AccountObjectId", type: "string" },
      { name: "Application", type: "string" },
      { name: "IPAddress", type: "string" },
      { name: "Country", type: "string" },
      { name: "City", type: "string" },
      { name: "LogonType", type: "string" },
      { name: "ErrorCode", type: "int" },
      { name: "FailureReason", type: "string" },
      { name: "ConditionalAccessStatus", type: "string" },
      { name: "RiskLevelAggregated", type: "string" },
      { name: "RiskState", type: "string" },
      { name: "IsManagedDevice", type: "bool" },
      { name: "DeviceName", type: "string" },
      { name: "ReportId", type: "long" }
    ]
  },
  {
    category: "Microsoft Defender for Identity",
    table: "IdentityLogonEvents",
    description: "Identity logon activity. Useful for reviewing account logons, protocols, source IP context, destinations, and failure reasons.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "AccountUpn", "DeviceName", "ActionType", "LogonType", "IPAddress", "FailureReason"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "AccountName", type: "string" },
      { name: "AccountDomain", type: "string" },
      { name: "AccountUpn", type: "string" },
      { name: "DeviceName", type: "string" },
      { name: "IPAddress", type: "string" },
      { name: "ActionType", type: "string" },
      { name: "LogonType", type: "string" },
      { name: "Protocol", type: "string" },
      { name: "FailureReason", type: "string" },
      { name: "DestinationDeviceName", type: "string" },
      { name: "DestinationPort", type: "int" },
      { name: "ReportId", type: "long" }
    ]
  },
  {
    category: "Microsoft Defender for Identity",
    table: "IdentityInfo",
    description: "Identity profile and enrichment details. Useful for reviewing account status, roles, groups, departments, tags, and risk level.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "AccountUpn", "AccountDisplayName", "Department", "IsAccountEnabled", "RiskLevel"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "AccountObjectId", type: "string" },
      { name: "AccountUpn", type: "string" },
      { name: "AccountDisplayName", type: "string" },
      { name: "AccountDomain", type: "string" },
      { name: "Department", type: "string" },
      { name: "JobTitle", type: "string" },
      { name: "City", type: "string" },
      { name: "Country", type: "string" },
      { name: "IsAccountEnabled", type: "bool" },
      { name: "AssignedRoles", type: "dynamic" },
      { name: "GroupMembership", type: "dynamic" },
      { name: "RiskLevel", type: "string" },
      { name: "Tags", type: "dynamic" }
    ]
  },
  {
    category: "Microsoft Defender for Identity",
    table: "IdentityQueryEvents",
    description: "Identity query activity. Useful for reviewing directory or authentication-related queries, protocols, devices, and actions.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "AccountUpn", "DeviceName", "QueryType", "Protocol", "ActionType"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "AccountName", type: "string" },
      { name: "AccountDomain", type: "string" },
      { name: "AccountUpn", type: "string" },
      { name: "DeviceName", type: "string" },
      { name: "QueryType", type: "string" },
      { name: "Query", type: "string" },
      { name: "Protocol", type: "string" },
      { name: "DestinationDeviceName", type: "string" },
      { name: "IPAddress", type: "string" },
      { name: "ActionType", type: "string" },
      { name: "ReportId", type: "long" }
    ]
  },
  {
    category: "Microsoft Defender for Identity",
    table: "IdentityDirectoryEvents",
    description: "Identity directory changes. Useful for reviewing account, group, target account, destination, and additional field context.",
    timeColumn: "Timestamp",
    defaultColumns: ["Timestamp", "AccountUpn", "ActionType", "TargetAccountUpn", "GroupName", "AdditionalFields"],
    columns: [
      { name: "Timestamp", type: "datetime" },
      { name: "AccountName", type: "string" },
      { name: "AccountDomain", type: "string" },
      { name: "AccountUpn", type: "string" },
      { name: "DeviceName", type: "string" },
      { name: "ActionType", type: "string" },
      { name: "TargetAccountUpn", type: "string" },
      { name: "TargetAccountDisplayName", type: "string" },
      { name: "GroupName", type: "string" },
      { name: "DestinationDeviceName", type: "string" },
      { name: "AdditionalFields", type: "dynamic" },
      { name: "ReportId", type: "long" }
    ]
  },
  {
    category: "Microsoft Entra ID",
    table: "AADServicePrincipalSignInLogs",
    description: "Service principal sign-in events. Useful for reviewing app identity activity, resources, result details, location, and risk context.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "ServicePrincipalName", "AppId", "ResourceDisplayName", "ResultType", "IPAddress"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "ServicePrincipalName", type: "string" },
      { name: "ServicePrincipalId", type: "string" },
      { name: "AppId", type: "string" },
      { name: "IPAddress", type: "string" },
      { name: "ResourceDisplayName", type: "string" },
      { name: "ResultType", type: "string" },
      { name: "ResultDescription", type: "string" },
      { name: "ConditionalAccessStatus", type: "string" },
      { name: "Location", type: "string" },
      { name: "RiskLevelAggregated", type: "string" },
      { name: "Status", type: "dynamic" }
    ]
  },
  {
    category: "Microsoft Entra ID",
    table: "AADNonInteractiveUserSignInLogs",
    description: "Non-interactive user sign-in events. Useful for reviewing background authentication, resources, result details, and device context.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "UserPrincipalName", "AppDisplayName", "ResourceDisplayName", "ResultType", "IPAddress"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "UserPrincipalName", type: "string" },
      { name: "UserDisplayName", type: "string" },
      { name: "AppDisplayName", type: "string" },
      { name: "IPAddress", type: "string" },
      { name: "ResourceDisplayName", type: "string" },
      { name: "ResultType", type: "string" },
      { name: "ResultDescription", type: "string" },
      { name: "ConditionalAccessStatus", type: "string" },
      { name: "Location", type: "string" },
      { name: "RiskLevelAggregated", type: "string" },
      { name: "DeviceDetail", type: "dynamic" },
      { name: "Status", type: "dynamic" }
    ]
  },
  {
    category: "Microsoft Entra ID",
    table: "AuditLogs",
    description: "Directory audit events. Useful for reviewing operations, results, initiating entities, target resources, and correlation IDs.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "OperationName", "Category", "Result", "LoggedByService", "CorrelationId"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "OperationName", type: "string" },
      { name: "Category", type: "string" },
      { name: "Result", type: "string" },
      { name: "ResultReason", type: "string" },
      { name: "ActivityDateTime", type: "datetime" },
      { name: "LoggedByService", type: "string" },
      { name: "InitiatedBy", type: "dynamic" },
      { name: "TargetResources", type: "dynamic" },
      { name: "AdditionalDetails", type: "dynamic" },
      { name: "CorrelationId", type: "string" }
    ]
  },
  {
    category: "Microsoft Entra ID",
    table: "AADProvisioningLogs",
    description: "Provisioning events. Useful for reviewing provisioning jobs, operations, source and target systems, identities, and changed properties.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "OperationName", "ResultType", "SourceSystem", "TargetSystem", "SourceIdentity", "TargetIdentity"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "JobId", type: "string" },
      { name: "CycleId", type: "string" },
      { name: "OperationName", type: "string" },
      { name: "ResultType", type: "string" },
      { name: "ResultDescription", type: "string" },
      { name: "SourceSystem", type: "string" },
      { name: "TargetSystem", type: "string" },
      { name: "SourceIdentity", type: "string" },
      { name: "TargetIdentity", type: "string" },
      { name: "ModifiedProperties", type: "dynamic" }
    ]
  },
  {
    category: "Microsoft Entra ID",
    table: "AADRiskyUsers",
    description: "Risky user records. Useful for reviewing user risk level, risk state, update time, details, and deleted status.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "UserPrincipalName", "UserDisplayName", "RiskLevel", "RiskState", "RiskDetail"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "UserPrincipalName", type: "string" },
      { name: "UserDisplayName", type: "string" },
      { name: "UserId", type: "string" },
      { name: "RiskLevel", type: "string" },
      { name: "RiskState", type: "string" },
      { name: "RiskLastUpdatedDateTime", type: "datetime" },
      { name: "RiskDetail", type: "string" },
      { name: "IsDeleted", type: "bool" }
    ]
  },
  {
    category: "Microsoft Sentinel / Log Analytics",
    table: "SecurityEvent",
    description: "Windows security events. Useful for reviewing event IDs, accounts, logon details, command lines, processes, and event data.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "Computer", "EventID", "Activity", "Account", "IpAddress", "CommandLine"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "Computer", type: "string" },
      { name: "EventID", type: "int" },
      { name: "Activity", type: "string" },
      { name: "Account", type: "string" },
      { name: "AccountType", type: "string" },
      { name: "LogonType", type: "int" },
      { name: "IpAddress", type: "string" },
      { name: "WorkstationName", type: "string" },
      { name: "ProcessName", type: "string" },
      { name: "CommandLine", type: "string" },
      { name: "ParentProcessName", type: "string" },
      { name: "SubjectAccount", type: "string" },
      { name: "TargetAccount", type: "string" },
      { name: "EventData", type: "dynamic" }
    ]
  },
  {
    category: "Microsoft Sentinel / Log Analytics",
    table: "Syslog",
    description: "Linux and network syslog messages. Useful for reviewing host, facility, severity, message text, process, and source context.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "Computer", "HostName", "SeverityLevel", "SyslogMessage", "ProcessName"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "Computer", type: "string" },
      { name: "HostName", type: "string" },
      { name: "Facility", type: "string" },
      { name: "SeverityLevel", type: "string" },
      { name: "SyslogMessage", type: "string" },
      { name: "ProcessName", type: "string" },
      { name: "ProcessID", type: "int" },
      { name: "SourceIP", type: "string" },
      { name: "Type", type: "string" }
    ]
  },
  {
    category: "Microsoft Sentinel / Log Analytics",
    table: "CommonSecurityLog",
    description: "Common security device logs. Useful for firewall and proxy investigations across source, destination, action, URL, and message fields.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "DeviceVendor", "DeviceProduct", "Activity", "SourceIP", "DestinationIP", "DeviceAction"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "DeviceVendor", type: "string" },
      { name: "DeviceProduct", type: "string" },
      { name: "DeviceVersion", type: "string" },
      { name: "DeviceEventClassID", type: "string" },
      { name: "Activity", type: "string" },
      { name: "LogSeverity", type: "string" },
      { name: "SourceIP", type: "string" },
      { name: "SourcePort", type: "int" },
      { name: "DestinationIP", type: "string" },
      { name: "DestinationPort", type: "int" },
      { name: "Protocol", type: "string" },
      { name: "DeviceAction", type: "string" },
      { name: "RequestURL", type: "string" },
      { name: "Message", type: "string" },
      { name: "AdditionalExtensions", type: "dynamic" }
    ]
  },
  {
    category: "Microsoft Sentinel / Log Analytics",
    table: "SecurityAlert",
    description: "Sentinel and security product alerts. Useful for reviewing alert severity, provider, tactics, entities, properties, and remediation notes.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "AlertName", "AlertSeverity", "ProviderName", "Tactics", "CompromisedEntity"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "SystemAlertId", type: "string" },
      { name: "AlertName", type: "string" },
      { name: "AlertSeverity", type: "string" },
      { name: "ProviderName", type: "string" },
      { name: "VendorName", type: "string" },
      { name: "ProductName", type: "string" },
      { name: "Tactics", type: "string" },
      { name: "Techniques", type: "string" },
      { name: "CompromisedEntity", type: "string" },
      { name: "Entities", type: "dynamic" },
      { name: "ExtendedProperties", type: "dynamic" },
      { name: "Description", type: "string" },
      { name: "RemediationSteps", type: "string" }
    ]
  },
  {
    category: "Microsoft Sentinel / Log Analytics",
    table: "SecurityIncident",
    description: "Microsoft Sentinel incidents. Useful for reviewing severity, status, owner, classification, related alerts, entities, and timestamps.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "IncidentNumber", "Title", "Severity", "Status", "Owner"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "IncidentNumber", type: "int" },
      { name: "Title", type: "string" },
      { name: "Severity", type: "string" },
      { name: "Status", type: "string" },
      { name: "Classification", type: "string" },
      { name: "ClassificationReason", type: "string" },
      { name: "Owner", type: "string" },
      { name: "ProviderName", type: "string" },
      { name: "IncidentUrl", type: "string" },
      { name: "Alerts", type: "dynamic" },
      { name: "Entities", type: "dynamic" },
      { name: "Comments", type: "dynamic" },
      { name: "LastModifiedTime", type: "datetime" },
      { name: "CreatedTime", type: "datetime" }
    ]
  },
  {
    category: "Microsoft Sentinel / Log Analytics",
    table: "Heartbeat",
    description: "Agent heartbeat records. Useful for checking whether expected log sources and monitored systems are still reporting.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "Computer", "OSType", "ResourceGroup", "ResourceType", "ComputerIP"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "Computer", type: "string" },
      { name: "OSType", type: "string" },
      { name: "OSName", type: "string" },
      { name: "OSMajorVersion", type: "string" },
      { name: "ResourceGroup", type: "string" },
      { name: "ResourceProvider", type: "string" },
      { name: "ResourceType", type: "string" },
      { name: "SubscriptionId", type: "string" },
      { name: "ComputerIP", type: "string" },
      { name: "Category", type: "string" }
    ]
  },
  {
    category: "Microsoft Sentinel / Log Analytics",
    table: "AzureActivity",
    description: "Azure control-plane activity. Useful for reviewing operations, callers, resource IDs, status, correlation IDs, and properties.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "OperationNameValue", "ActivityStatusValue", "Caller", "CallerIpAddress", "ResourceGroup"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "OperationNameValue", type: "string" },
      { name: "OperationName", type: "string" },
      { name: "ActivityStatusValue", type: "string" },
      { name: "ActivitySubstatusValue", type: "string" },
      { name: "ResourceGroup", type: "string" },
      { name: "ResourceProviderValue", type: "string" },
      { name: "ResourceId", type: "string" },
      { name: "Caller", type: "string" },
      { name: "CallerIpAddress", type: "string" },
      { name: "CategoryValue", type: "string" },
      { name: "CorrelationId", type: "string" },
      { name: "Properties", type: "dynamic" }
    ]
  },
  {
    category: "Microsoft Sentinel / Log Analytics",
    table: "OfficeActivity",
    description: "Microsoft 365 audit activity. Useful for reviewing workload, operation, user, client IP, object, file, site, and changed properties.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "OfficeWorkload", "Operation", "UserId", "ClientIP", "ResultStatus", "ObjectId"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "OfficeWorkload", type: "string" },
      { name: "Operation", type: "string" },
      { name: "UserId", type: "string" },
      { name: "UserType", type: "string" },
      { name: "ClientIP", type: "string" },
      { name: "ResultStatus", type: "string" },
      { name: "ObjectId", type: "string" },
      { name: "RecordType", type: "string" },
      { name: "SiteUrl", type: "string" },
      { name: "SourceFileName", type: "string" },
      { name: "SourceRelativeUrl", type: "string" },
      { name: "Parameters", type: "dynamic" },
      { name: "ModifiedProperties", type: "dynamic" }
    ]
  },
  {
    category: "Microsoft Sentinel / Log Analytics",
    table: "W3CIISLog",
    description: "IIS web server logs. Useful for reviewing methods, URI paths, query strings, status codes, user agents, and response time.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "Computer", "csMethod", "csUriStem", "cIP", "scStatus", "TimeTaken"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "Computer", type: "string" },
      { name: "sSiteName", type: "string" },
      { name: "csMethod", type: "string" },
      { name: "csUriStem", type: "string" },
      { name: "csUriQuery", type: "string" },
      { name: "sPort", type: "int" },
      { name: "cIP", type: "string" },
      { name: "csUserAgent", type: "string" },
      { name: "scStatus", type: "int" },
      { name: "scSubStatus", type: "int" },
      { name: "scWin32Status", type: "int" },
      { name: "TimeTaken", type: "int" },
      { name: "Referer", type: "string" }
    ]
  },
  {
    category: "Microsoft Sentinel / Log Analytics",
    table: "Event",
    description: "General Windows event records. Useful for reviewing event logs, sources, event IDs, rendered descriptions, user names, and event data.",
    timeColumn: "TimeGenerated",
    defaultColumns: ["TimeGenerated", "Computer", "EventLog", "Source", "EventID", "EventLevelName"],
    columns: [
      { name: "TimeGenerated", type: "datetime" },
      { name: "Computer", type: "string" },
      { name: "EventLog", type: "string" },
      { name: "Source", type: "string" },
      { name: "EventID", type: "int" },
      { name: "EventLevelName", type: "string" },
      { name: "RenderedDescription", type: "string" },
      { name: "ParameterXml", type: "string" },
      { name: "EventData", type: "dynamic" },
      { name: "UserName", type: "string" }
    ]
  },
];
